using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging;

namespace PsiFlow.Agenda.Infrastructure.Persistence;

public sealed class AgendaDatabaseInitializer : IHostedService
{
    private readonly IServiceProvider _serviceProvider;
    private readonly ILogger<AgendaDatabaseInitializer> _logger;

    public AgendaDatabaseInitializer(IServiceProvider serviceProvider, ILogger<AgendaDatabaseInitializer> logger)
    {
        _serviceProvider = serviceProvider;
        _logger = logger;
    }

    public async Task StartAsync(CancellationToken cancellationToken)
    {
        using var scope = _serviceProvider.CreateScope();
        var context = scope.ServiceProvider.GetRequiredService<AgendaDbContext>();
        await context.Database.EnsureCreatedAsync(cancellationToken);
        await context.Database.ExecuteSqlRawAsync("""
            CREATE SCHEMA IF NOT EXISTS agenda;

            CREATE TABLE IF NOT EXISTS agenda.availability (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "TenantId" integer NOT NULL,
                "Weekday" integer NOT NULL,
                "StartTime" time without time zone NOT NULL,
                "EndTime" time without time zone NOT NULL,
                "SlotDurationMinutes" integer NOT NULL,
                "Modality" text NOT NULL,
                "Timezone" text NOT NULL,
                "IsActive" boolean NOT NULL,
                "CreatedAt" timestamp with time zone NOT NULL,
                "UpdatedAt" timestamp with time zone NULL,
                "IsDeleted" boolean NOT NULL
            );

            CREATE TABLE IF NOT EXISTS agenda.schedule_blocks (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "TenantId" integer NOT NULL,
                "StartsAt" timestamp with time zone NOT NULL,
                "EndsAt" timestamp with time zone NOT NULL,
                "Reason" text NULL,
                "CreatedBy" integer NOT NULL,
                "CreatedAt" timestamp with time zone NOT NULL,
                "UpdatedAt" timestamp with time zone NULL,
                "IsDeleted" boolean NOT NULL
            );
            """, cancellationToken);
        _logger.LogInformation("Schema do banco de agenda verificado.");
    }

    public Task StopAsync(CancellationToken cancellationToken) => Task.CompletedTask;
}
