using BuildingBlocks.Results;
using ClinicalRecords.Application.Contracts;
using ClinicalRecords.Domain.Aggregates;
using Microsoft.EntityFrameworkCore;
using PsiFlow.ClinicalRecords.Infrastructure.Persistence;

namespace ClinicalRecords.Infrastructure.Services;

public sealed class ClinicalRecordWorkflowService(ClinicalRecordsDbContext db) : IClinicalRecordWorkflowService
{
    public async Task<Result<object>> GetRecordByPatientAsync(int patientId, int tenantId, CancellationToken ct) => await OkOrNotFound(db.MedicalRecords.AsNoTracking().FirstOrDefaultAsync(x => x.PatientId == patientId && x.TenantId == tenantId, ct));
    public async Task<Result<object>> CreateRecordAsync(int patientId, int tenantId, string? name, CancellationToken ct) { var r = new MedicalRecord { TenantId = tenantId, PatientId = patientId, Name = string.IsNullOrWhiteSpace(name) ? $"Patient {patientId}" : name }; db.MedicalRecords.Add(r); await db.SaveChangesAsync(ct); return Result.Success<object>(r); }
    public async Task<Result<object>> GetRecordAsync(int recordId, int tenantId, CancellationToken ct) => await OkOrNotFound(db.MedicalRecords.AsNoTracking().FirstOrDefaultAsync(x => x.Id == recordId && x.TenantId == tenantId, ct));
    public async Task<Result<object>> GetAnamnesisAsync(int recordId, int tenantId, CancellationToken ct) { var a = await GetOrCreateAnamnesis(recordId, tenantId, ct); return Result.Success<object>(a); }
    public async Task<Result> AutosaveAnamnesisAsync(int recordId, int tenantId, string? ciphertext, string? nonce, string? tag, CancellationToken ct) { var a = await GetOrCreateAnamnesis(recordId, tenantId, ct); a.DraftCiphertext = ciphertext; a.DraftNonce = nonce; a.DraftTag = tag; a.DraftUpdatedAt = DateTime.UtcNow; await db.SaveChangesAsync(ct); return Result.Success(); }
    public async Task<Result<object>> PublishAnamnesisVersionAsync(int recordId, int tenantId, int userId, string? reason, CancellationToken ct) { var a = await GetOrCreateAnamnesis(recordId, tenantId, ct); var n = await db.AnamnesisVersions.CountAsync(x => x.AnamnesisId == a.Id, ct) + 1; var v = new AnamnesisVersion { TenantId = tenantId, AnamnesisId = a.Id, VersionNumber = n, Ciphertext = a.DraftCiphertext ?? string.Empty, Nonce = a.DraftNonce ?? string.Empty, Tag = a.DraftTag ?? string.Empty, CreatedBy = userId, Reason = reason }; db.AnamnesisVersions.Add(v); await db.SaveChangesAsync(ct); a.CurrentVersionId = v.Id; await db.SaveChangesAsync(ct); return Result.Success<object>(v); }
    public async Task<Result<object>> GetEvolutionAsync(int sessionId, int tenantId, CancellationToken ct) { var e = await GetOrCreateEvolution(sessionId, tenantId, ct); return Result.Success<object>(e); }
    public async Task<Result> AutosaveEvolutionAsync(int sessionId, int tenantId, string? ciphertext, string? nonce, string? tag, CancellationToken ct) { var e = await GetOrCreateEvolution(sessionId, tenantId, ct); e.DraftCiphertext = ciphertext; e.DraftNonce = nonce; e.DraftTag = tag; e.DraftUpdatedAt = DateTime.UtcNow; await db.SaveChangesAsync(ct); return Result.Success(); }
    public async Task<Result<object>> PublishEvolutionVersionAsync(int sessionId, int tenantId, int userId, string? reason, CancellationToken ct) { var e = await GetOrCreateEvolution(sessionId, tenantId, ct); var n = await db.EvolutionVersions.CountAsync(x => x.EvolutionId == e.Id, ct) + 1; var v = new EvolutionVersion { TenantId = tenantId, EvolutionId = e.Id, VersionNumber = n, Ciphertext = e.DraftCiphertext ?? string.Empty, Nonce = e.DraftNonce ?? string.Empty, Tag = e.DraftTag ?? string.Empty, CreatedBy = userId, Reason = reason }; db.EvolutionVersions.Add(v); await db.SaveChangesAsync(ct); e.CurrentVersionId = v.Id; await db.SaveChangesAsync(ct); return Result.Success<object>(v); }
    public async Task<Result<object>> GetEvolutionVersionsAsync(int sessionId, int tenantId, CancellationToken ct) { var e = await db.Evolutions.AsNoTracking().FirstOrDefaultAsync(x => x.SessionId == sessionId && x.TenantId == tenantId, ct); if (e is null) return Result.Success<object>(Array.Empty<object>()); return Result.Success<object>(await db.EvolutionVersions.AsNoTracking().Where(x => x.EvolutionId == e.Id).OrderByDescending(x => x.VersionNumber).ToListAsync(ct)); }
    public async Task<Result<object>> GetAuditLogAsync(int recordId, int tenantId, CancellationToken ct) => Result.Success<object>(await db.ClinicalAuditLogs.AsNoTracking().Where(x => x.ResourceId == recordId && x.TenantId == tenantId).ToListAsync(ct));
    private async Task<Anamnesis> GetOrCreateAnamnesis(int recordId, int tenantId, CancellationToken ct) { var a = await db.Anamneses.FirstOrDefaultAsync(x => x.RecordId == recordId && x.TenantId == tenantId, ct); if (a is not null) return a; a = new Anamnesis { RecordId = recordId, TenantId = tenantId }; db.Anamneses.Add(a); await db.SaveChangesAsync(ct); return a; }
    private async Task<Evolution> GetOrCreateEvolution(int sessionId, int tenantId, CancellationToken ct) { var e = await db.Evolutions.FirstOrDefaultAsync(x => x.SessionId == sessionId && x.TenantId == tenantId, ct); if (e is not null) return e; var recordId = await db.MedicalRecords.Where(x => x.TenantId == tenantId).Select(x => x.Id).FirstOrDefaultAsync(ct); e = new Evolution { SessionId = sessionId, TenantId = tenantId, RecordId = recordId }; db.Evolutions.Add(e); await db.SaveChangesAsync(ct); return e; }
    private static async Task<Result<object>> OkOrNotFound<T>(Task<T?> task) where T : class => await task is { } value ? Result.Success<object>(value) : Result.Failure<object>(Error.NotFound("Clinical record not found."));
}
